@startuml
|Invocateur|
|Démon|

|Invocateur|
if (La FIOFO existe ?) then (Non)
    :Erreur;
    end 
else (Oui)
    :Envoyer "TIME";
    split 
        :Écouter avec Timeout;
    split again 
        |Démon|
        -> <b>"TIME";
        :Recevoir "TIME";
        :Envoyer la "date de base";

    end split 
    |Invocateur|
    -> <b> date;
    if (Erreur Timeout ?) then (Oui)
        :Erreur;
        end
    else (Non)
        :Recevoir la date;
        :Afficher la date;
        stop
    endif     

@enduml