@startuml

|invokator|
start
:attente entrée commande;
:reception du durée et trasmission de la demande au démon;
fork
    :attente du message;
fork again
    |daemon|
    if (le démon est démarré) then (oui)
        |invokator| 
        :reception du message positif;
    else (non)
        |invokator|
        :affichage message démon non démarré;
        stop
    endif
end fork

fork
    :attente du message;
fork again
    |daemon|
    :recherche date début dans le fichier;
    :envoie de la date (sous forme de timestamp);
    |invokator|
end fork
:convertit timestamp en jj-mm-aaaa hh:mm:ss;
:affichage date;
end

@enduml