@startuml
|Invocateur|
|Démon|

|Invocateur|
if (La FIOFO existe ?) then (Non)
    :Erreur;
    end 
else (Oui)
    :Envoyer "DURATION";
    split 
        :Écouter avec Timeout;
    split again 
        |Démon|
        -> <b>"DURATION";
        :Recevoir "DURATION";
        :Envoyer la différence entre la date\nactuelle et la "date de base";

    end split 
    |Invocateur|
    -> <b> durée;
    if (Erreur Timeout ?) then (Oui)
        :Erreur;
        end
    else (Non)
        :Recevoir la durée;
        :Afficher la durée;
        stop
    endif     

@enduml