@startuml
|Invocateur|
|Démon|

|Invocateur|
if (La FIOFO existe ?) then (Non)
    :Erreur;
    end 
else (Oui)
    :Envoyer "RESET";
    split 
        stop 
    split again 
        |Démon|
        :Recevoir "Reset";
        :Modifier la valeur de la "date de base";
        detach
    end split 

@enduml