@startuml 
|Invoker|
start 
fork
|Invoker|
    :Création de la FIFO;
    if (la fifo a bienété créée) then (Oui)
    else (Non)
        :Supression de la fifo precedente;        
        :Création de la FIFO;
    endif
    stop
    
fork again
    :Executer le programme Démon;
    |Deamon|
    start
    :En attente d'événement;
    detach
@enduml 