@startuml 
-[hidden]->

|Invoker|
start 


if (La fifo existe) then (Non)
    :Démon pas en vie;
    end
else (Oui)
    :Ping le démon;
    split
        |Invoker|
        :Écouter avec Timeout;   
        |Deamon|      
    
    split again 
        -> <b>"PING";
        :Reçoit le PING;
        :Envoyer un PONG;
        -> <b>"PONG";
        
    end split

    |Invoker|
    if (Timeout Error) then (Oui)
        :Démon pas en vie;
        end

    else (Non)
        if (Message reçu == PONG) then (Oui)
            :Démon est en vie;
            stop
        else (Non)
            :Démon pas en vie;
            end
        endif 

    endif 
endif

@enduml 