@startuml
|Invocateur|
|Démon|

|Invocateur|
if (La FIFO existe ?) then (Non)
    :Erreur;
    end
else (Oui)
    :Envoyer "KILL";
    split
        stop
    split again
        |Démon|
        -> <b>"KILL";
        :Arrêter la boucle;
        :Arrêter le démon;
        stop
    end split

endif

@enduml 